image: python:3.12

definitions:
  caches:
    pip: ~/.cache/pip
    poetry: ~/.cache/pypoetry

pipelines:
  branches:
    release:
      - step:
          name: Build + Run + Tests
          caches:
            - pip
            - poetry
          script:
            # Atualiza pip e instala Poetry
            - python -m pip install --upgrade pip
            - pip install poetry

            # Instala dependências do projeto via Poetry
            - poetry install

            # Instala plugin HTML do pytest dentro do ambiente do Poetry
            - poetry run pip install pytest-html

            # Clona repositório externo
            - echo "Clonando repositório sensedia/apis-repo..."
            - git clone --depth 1 "https://${BB_USERNAME}:${BB_REPO_TOKEN}@bitbucket.org/sensedia/apis-repo.git" ./external-repo
            - ls -la ./external-repo

            #debug variavel mavem
            - echo "MAVEN_USERNAME: $MAVEN_USERNAME"

            # Gera o .env
            - printf "PROD_URL=%s\nAUTHORIZATION=%s\nREQUEST_TIMEOUT=%s\nAPI_ID=%s\n" \
              "$PROD_URL" "$AUTHORIZATION" "$REQUEST_TIMEOUT" "$API_ID" > .env

            # Executa aplicação
            - poetry run python src/apiops_orchestrator/main.py

            # Executa testes + relatórios (JUnit + HTML)
            - mkdir -p test-results
            - poetry run pytest --junitxml=test-results/pytest-results.xml --html=test-results/pytest-report.html --self-contained-html
          artifacts:
            - test-results/**
            - mkdir -p test-results
            - poetry run pytest --junitxml=test-results/pytest-results.xml --html=test-results/pytest-report.html --self-contained-html
          artifacts:
            - test-results/**
